### ISSUE TITLE
Design the list of entries

### ISSUE THREAD

**Issue by rgoj** [rgoj/project-cycles-visualisation#6]

**Comment by MonkeyRose** [comment]
Just thought... once we get the secondary subsystems showing, or even before, the key in the third image could highlight which other subsystems are involved.

![190114_project_cycles_design_01](https://user-images.githubusercontent.com/46627969/51323863-3b446a00-1a61-11e9-8c83-6a9dec2308a9.jpg)
![190114_project_cycles_design_02](https://user-images.githubusercontent.com/46627969/51323864-3b446a00-1a61-11e9-8fd3-efaebe0c25d8.jpg)
![190114_project_cycles_design_03](https://user-images.githubusercontent.com/46627969/51323866-3bdd0080-1a61-11e9-9ee6-dc21646ce985.jpg)

**Comment by rgoj** [comment]
> Just thought... once we get the secondary subsystems showing, or even before, the key in the third image could highlight which other subsystems are involved.

Nice idea! Oh, the designs look so awesome displayed next to each other on github : )

**Comment by rgoj** [comment]
> Just thought... once we get the secondary subsystems showing, or even before, the key in the third image could highlight which other subsystems are involved.

Now implemented!
